//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolumlers
    {
        public Bolumlers()
        {
            this.CalismaAlanlaris = new HashSet<CalismaAlanlaris>();
            this.UyeBolums = new HashSet<UyeBolums>();
        }
    
        public int bolum_id { get; set; }
        public string bolum_adi { get; set; }
        public int bolum_kodu { get; set; }
        public int bolum_FakulteId { get; set; }
    
        public virtual Fakultelers Fakultelers { get; set; }
        public virtual ICollection<CalismaAlanlaris> CalismaAlanlaris { get; set; }
        public virtual ICollection<UyeBolums> UyeBolums { get; set; }
    }
}
