//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyuruKapsamis
    {
        public int duyuruKapsam_id { get; set; }
        public int duyuru_id { get; set; }
        public int calismaAlani_id { get; set; }
    
        public virtual CalismaAlanlaris CalismaAlanlaris { get; set; }
        public virtual Duyurulars Duyurulars { get; set; }
    }
}
