//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fakultelers
    {
        public Fakultelers()
        {
            this.Bolumlers = new HashSet<Bolumlers>();
        }
    
        public int fakulte_id { get; set; }
        public string fakulte_adi { get; set; }
        public int fakulte_kodu { get; set; }
    
        public virtual ICollection<Bolumlers> Bolumlers { get; set; }
    }
}
