//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilcelers
    {
        public Ilcelers()
        {
            this.Uyelers = new HashSet<Uyelers>();
        }
    
        public int ilce_id { get; set; }
        public string ilce_adi { get; set; }
        public int ilce_SehirId { get; set; }
    
        public virtual Sehirlers Sehirlers { get; set; }
        public virtual ICollection<Uyelers> Uyelers { get; set; }
    }
}
