//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MezunTakipDbEntities : DbContext
    {
        public MezunTakipDbEntities()
            : base("name=MezunTakipDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Bolumlers> Bolumlers { get; set; }
        public DbSet<CalismaAlanlaris> CalismaAlanlaris { get; set; }
        public DbSet<DuyuruBasvurus> DuyuruBasvurus { get; set; }
        public DbSet<DuyuruKapsamis> DuyuruKapsamis { get; set; }
        public DbSet<Duyurulars> Duyurulars { get; set; }
        public DbSet<Fakultelers> Fakultelers { get; set; }
        public DbSet<Ilcelers> Ilcelers { get; set; }
        public DbSet<OgrenimDurumlaris> OgrenimDurumlaris { get; set; }
        public DbSet<Sehirlers> Sehirlers { get; set; }
        public DbSet<SirketAdres> SirketAdres { get; set; }
        public DbSet<Sirketlers> Sirketlers { get; set; }
        public DbSet<SirketTels> SirketTels { get; set; }
        public DbSet<SirketWebs> SirketWebs { get; set; }
        public DbSet<UyeAdres> UyeAdres { get; set; }
        public DbSet<UyeBolums> UyeBolums { get; set; }
        public DbSet<UyeCalismaAlanis> UyeCalismaAlanis { get; set; }
        public DbSet<Uyelers> Uyelers { get; set; }
        public DbSet<UyeMails> UyeMails { get; set; }
        public DbSet<UyeOgrenimDurumus> UyeOgrenimDurumus { get; set; }
        public DbSet<UyeSirkets> UyeSirkets { get; set; }
        public DbSet<UyeTels> UyeTels { get; set; }
        public DbSet<UyeBolumView> UyeBolumView { get; set; }
        public DbSet<UyeCalismaAlaniView> UyeCalismaAlaniView { get; set; }
        public DbSet<UyeSirketView> UyeSirketView { get; set; }
        public DbSet<DuyurularView> DuyurularView { get; set; }
        public DbSet<DuyuruBasvuruView> DuyuruBasvuruView { get; set; }
        public DbSet<DuyuruKapsamView> DuyuruKapsamView { get; set; }
    }
}
