//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehirlers
    {
        public Sehirlers()
        {
            this.Ilcelers = new HashSet<Ilcelers>();
        }
    
        public int sehir_id { get; set; }
        public string sehir_adi { get; set; }
        public int sehir_kodu { get; set; }
    
        public virtual ICollection<Ilcelers> Ilcelers { get; set; }
    }
}
