//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirketlers
    {
        public Sirketlers()
        {
            this.SirketAdres = new HashSet<SirketAdres>();
            this.SirketTels = new HashSet<SirketTels>();
            this.SirketWebs = new HashSet<SirketWebs>();
            this.UyeSirkets = new HashSet<UyeSirkets>();
        }
    
        public int sirket_id { get; set; }
        public string sirket_adi { get; set; }
    
        public virtual ICollection<SirketAdres> SirketAdres { get; set; }
        public virtual ICollection<SirketTels> SirketTels { get; set; }
        public virtual ICollection<SirketWebs> SirketWebs { get; set; }
        public virtual ICollection<UyeSirkets> UyeSirkets { get; set; }
    }
}
