//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyelers
    {
        public Uyelers()
        {
            this.DuyuruBasvurus = new HashSet<DuyuruBasvurus>();
            this.Duyurulars = new HashSet<Duyurulars>();
            this.UyeAdres = new HashSet<UyeAdres>();
            this.UyeBolums = new HashSet<UyeBolums>();
            this.UyeCalismaAlanis = new HashSet<UyeCalismaAlanis>();
            this.UyeMails = new HashSet<UyeMails>();
            this.UyeOgrenimDurumus = new HashSet<UyeOgrenimDurumus>();
            this.UyeSirkets = new HashSet<UyeSirkets>();
            this.UyeTels = new HashSet<UyeTels>();
        }
    
        public string uye_tc { get; set; }
        public int uye_id { get; set; }
        public string uye_ad { get; set; }
        public string uye_soyad { get; set; }
        public string uye_sifre { get; set; }
        public Nullable<System.DateTime> uye_dogumTarihi { get; set; }
        public int uye_cinsiyet { get; set; }
        public Nullable<int> uye_askerlikDurumu { get; set; }
        public byte[] uye_foto { get; set; }
        public int uye_dogumYeri_id { get; set; }
    
        public virtual ICollection<DuyuruBasvurus> DuyuruBasvurus { get; set; }
        public virtual ICollection<Duyurulars> Duyurulars { get; set; }
        public virtual Ilcelers Ilcelers { get; set; }
        public virtual ICollection<UyeAdres> UyeAdres { get; set; }
        public virtual ICollection<UyeBolums> UyeBolums { get; set; }
        public virtual ICollection<UyeCalismaAlanis> UyeCalismaAlanis { get; set; }
        public virtual ICollection<UyeMails> UyeMails { get; set; }
        public virtual ICollection<UyeOgrenimDurumus> UyeOgrenimDurumus { get; set; }
        public virtual ICollection<UyeSirkets> UyeSirkets { get; set; }
        public virtual ICollection<UyeTels> UyeTels { get; set; }
    }
}
