//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeSirketView
    {
        public int uyeSirket_id { get; set; }
        public string uyeSirket_durum { get; set; }
        public string sirket_adi { get; set; }
        public string sirket_adres { get; set; }
        public string sirket_tel { get; set; }
        public string sirket_web { get; set; }
        public string uye_tc { get; set; }
    }
}
