//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunTakipDx
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeTels
    {
        public int uyeTel_id { get; set; }
        public string uye_tel { get; set; }
        public string uye_tc { get; set; }
    
        public virtual Uyelers Uyelers { get; set; }
    }
}
